export const PUSH_PLUS_BUTTON_REQUEST ="PUSH_PLUS_BUTTON_REQUEST";
export const PUSH_PLUS_BUTTON_SUCCESS ="PUSH_PLUS_BUTTON_SUCCESS";
export const PUSH_MINUS_BUTTON_REQUEST ="PUSH_MINUS_BUTTON_REQUEST";
export const PUSH_MINUS_BUTTON_SUCCESS ="PUSH_MINUS_BUTTON_SUCCESS";
